"""add vk fields to user

Revision ID: a2f8e3f5495c
Revises: 
Create Date: 2025-07-03 20:30:43.899565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f8e3f5495c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('vk_refresh_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vk_refresh_token')
    op.drop_column('users', 'vk_access_token')
    # ### end Alembic commands ### 