"""add vk_id and account flags to user model

Revision ID: add_vk_id_and_account_flags
Revises: a2f8e3f5495c
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_vk_id_and_account_flags'
down_revision = 'a2f8e3f5495c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_vk_account', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('has_google_account', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('has_google_sheet', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_column('users', 'has_google_sheet')
    op.drop_column('users', 'has_google_account')
    op.drop_column('users', 'has_vk_account')
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ### 