"""fix vk fields migration

Revision ID: fix_vk_fields_migration
Revises: add_vk_id_and_account_flags
Create Date: 2024-12-19 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fix_vk_fields_migration'
down_revision = 'add_vk_id_and_account_flags'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Проверяем существование колонок и добавляем недостающие
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]
    
    # Добавляем недостающие колонки если их нет
    if 'vk_id' not in existing_columns:
        op.add_column('users', sa.Column('vk_id', sa.String(), nullable=True))
        op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    
    if 'has_vk_account' not in existing_columns:
        op.add_column('users', sa.Column('has_vk_account', sa.Boolean(), nullable=True, server_default='false'))
    
    if 'has_google_account' not in existing_columns:
        op.add_column('users', sa.Column('has_google_account', sa.Boolean(), nullable=True, server_default='false'))
    
    if 'has_google_sheet' not in existing_columns:
        op.add_column('users', sa.Column('has_google_sheet', sa.Boolean(), nullable=True, server_default='false'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем добавленные колонки
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'has_google_sheet' in existing_columns:
        op.drop_column('users', 'has_google_sheet')
    
    if 'has_google_account' in existing_columns:
        op.drop_column('users', 'has_google_account')
    
    if 'has_vk_account' in existing_columns:
        op.drop_column('users', 'has_vk_account')
    
    if 'vk_id' in existing_columns:
        op.drop_index(op.f('ix_users_vk_id'), table_name='users')
        op.drop_column('users', 'vk_id')
    
    # ### end Alembic commands ### 